---
# tasks file for nginx
- name: registration nginx yum repository
  ansible.builtin.yum_repository:
    name: "{{ nginx_repo_name }}"
    description: nginx stable repo
    file: nginx
    baseurl: http://nginx.org/packages/amzn2/$releasever/$basearch/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key
    #module_hotfixes: true
    owner: root
    group: root
    mode: '0644'
    state: present

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present
    enablerepo:
      - "{{ nginx_repo_name }}"
  become: yes
  notify: start_nginx

- name: edit rails_conf
  ansible.builtin.template:
    src: roles/nginx/templates/rails_conf.j2
    dest: /etc/nginx/conf.d/rails.conf
